### ISSUE TITLE
Figure out if/else logic for process functions

### ISSUE THREAD

**Issue by xaviernogueira** [EcohydrologyTeam/ClearWater-modules-python#31]
**Problem:**
As of now, I use `xarray.apply_ufunc()` to run model process functions in order to calculate dynamic/state variables. The problem with this is it only works for cell-based math operations, not if/else logic.

**Tasks:**

- [ ] Figure out the best way to make if/else work without causing a rate-limiting step in model performance (ideally it should be JIT compiled).
- [ ] Create issues for @imscw95 and @kewalak to update if/else process function structure IF necessary.
- [ ] Go back to TSM and update the logic on the if/else process functions.
- [ ] Create a test for whatever logic I implement. Have the test pass reliably with a few different process function structures.
