### ISSUE TITLE
Add CodeCov tracking to our automated test suite

### ISSUE THREAD

**Issue by xaviernogueira** [EcohydrologyTeam/ClearWater-modules-python#37]
[CodeCov](https://about.codecov.io/) allows us to track our test suites coverage of our code and visualize it line by line. This makes it easy to see what code is untested, and to make sure new PRs aren't dropping coverage significantly.

I had to wait for EcohydrologyTeam admin permission to grant CodeCov access to the repo, but that has been given, so now I can proceed and set it up to be automated.

- [ ] Add CodeCov config to `tests.yml`
- [ ] Add README badges showing test status as well as coverage status.
- [ ] Make sure everything works.
